name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 24
          cache: maven

      - name: Set up ANTLR
        run: |
          curl -sSL -o $HOME/antlr-4.13.2-complete.jar https://www.antlr.org/download/antlr-4.13.2-complete.jar
          echo 'alias antlr="java -jar $HOME/antlr-4.13.2-complete.jar"' >> $GITHUB_ENV

      - name: Build
        run: ./refresh-grammar.sh

      - name: Run tests
        working-directory: SSC-C
        run: mvn test
